version: '3'

services:
  apps:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
      - 3001:3001
      - 3002:3002
      - 3003:3003
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASS: null
      GATEWAY_PORT: 3000
      WORLD_PORT: 3001
    depends_on:
      - redis
      - rabbitmq
    volumes:
      - ./:/app
    networks:
      - my-network
    command: sh -c "sleep 10 && npm run build:all && npm run start:prod:all"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - my-network
    volumes:
      - /var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    networks:
      - my-network

volumes:
  data:


networks:
  my-network:
